//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CambiosEstatus
    {
        public int ID_CambioEstatus { get; set; }
        public int ID_Seguimiento { get; set; }
        public int ID_EstatusInicial { get; set; }
        public int ID_EstatusFinal { get; set; }
        public System.TimeSpan TiempoTranscurrido { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public string UserID { get; set; }
    
        public virtual Estatus Estatus { get; set; }
        public virtual Estatus Estatus1 { get; set; }
        public virtual Seguimientos Seguimientos { get; set; }
    }
}
