//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int ID_Chat { get; set; }
        public int ID_Conductor { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Mensaje { get; set; }
        public Nullable<int> Es_Conductor { get; set; }
        public Nullable<int> ID_Despacho { get; set; }
        public Nullable<int> ID_Operador { get; set; }
    
        public virtual Conductores Conductores { get; set; }
        public virtual Despachos Despachos { get; set; }
        public virtual Operadores Operadores { get; set; }
    }
}
