//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesAbonados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientesAbonados()
        {
            this.DireccionesAlternativas = new HashSet<DireccionesAlternativas>();
            this.UsuariosAbonados = new HashSet<UsuariosAbonados>();
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int ID_ClienteAbonado { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public bool Telefono_EsCelular { get; set; }
        public decimal Limite_Credito { get; set; }
        public string Email { get; set; }
        public string Clave_Automatica { get; set; }
        public string Observaciones { get; set; }
        public bool Habilitado { get; set; }
        public bool Reportes { get; set; }
        public bool Servicios_Automaticos { get; set; }
        public System.DateTime Fecha_Alta { get; set; }
        public Nullable<System.DateTime> Fecha_Baja { get; set; }
        public int ID_Calle { get; set; }
        public int Numero_Exterior { get; set; }
        public string Numero_Interior { get; set; }
        public int CP { get; set; }
        public string RFC { get; set; }
        public int Dia_Pago { get; set; }
        public int ID_Banco { get; set; }
        public string Clabe { get; set; }
        public int ID_TipoAviso { get; set; }
        public int ID_FormaPago { get; set; }
        public int ID_Afiliado { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public string UserID { get; set; }
    
        public virtual Afiliados Afiliados { get; set; }
        public virtual Bancos Bancos { get; set; }
        public virtual Calles Calles { get; set; }
        public virtual FormasPago FormasPago { get; set; }
        public virtual TiposAvisos TiposAvisos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DireccionesAlternativas> DireccionesAlternativas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosAbonados> UsuariosAbonados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
