//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.DireccionesAlternativas = new HashSet<DireccionesAlternativas>();
            this.Reservas = new HashSet<Reservas>();
            this.Usuario_App = new HashSet<Usuario_App>();
        }
    
        public int ID_Cliente { get; set; }
        public string Nombre { get; set; }
        public int ID_Calle_Origen { get; set; }
        public int Numero_Exterior_Origen { get; set; }
        public string Numero_Interior_Origen { get; set; }
        public int ID_Calle_Destino { get; set; }
        public int Numero_Exterior_Destino { get; set; }
        public string Numero_Interior_Destino { get; set; }
        public int ID_Afiliado { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public string Telefono { get; set; }
    
        public virtual Afiliados Afiliados { get; set; }
        public virtual Calles Calles { get; set; }
        public virtual Calles Calles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DireccionesAlternativas> DireccionesAlternativas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservas> Reservas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_App> Usuario_App { get; set; }
    }
}
