//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conductores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conductores()
        {
            this.Sanciones = new HashSet<Sanciones>();
            this.Vehiculos_Conductores = new HashSet<Vehiculos_Conductores>();
            this.Chat = new HashSet<Chat>();
        }
    
        public int ID_Conductor { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int ID_Calle { get; set; }
        public int Numero_Exterior { get; set; }
        public string Numero_Interior { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string RFC { get; set; }
        public bool Habilitado { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public int ID_Turno { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public string UserID { get; set; }
        public int ID_Flota { get; set; }
        public string UserID_Conductor { get; set; }
        public string Contrasena { get; set; }
        public string Usuario { get; set; }
        public string token { get; set; }
        public string NoLicencia { get; set; }
        public string NoTarjeton { get; set; }
        public int Vigencia_Licencia { get; set; }
        public int Vigencia_Tarjeton { get; set; }
        public bool Liquido { get; set; }
        public string Archivo_CartaFianza { get; set; }
        public string Archivo_INE { get; set; }
        public string Archivo_Domicilio { get; set; }
        public string Archivo_Tarjeton { get; set; }
        public string Archivo_Licencia { get; set; }
        public string Archivo_Antidoping { get; set; }
        public string Archivo_NoAntecedentes { get; set; }
    
        public virtual Calles Calles { get; set; }
        public virtual Flotas Flotas { get; set; }
        public virtual Turnos Turnos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sanciones> Sanciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculos_Conductores> Vehiculos_Conductores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chat> Chat { get; set; }
    }
}
