//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuraciones
    {
        public string Atributo { get; set; }
        public string Valor { get; set; }
        public int EsConfiguracionChofer { get; set; }
        public string TipoDato { get; set; }
        public int ID { get; set; }
    }
}
