//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuponesSeries
    {
        public int idCuponSerie { get; set; }
        public string Serie { get; set; }
        public int Dominio { get; set; }
        public int Consecutivo { get; set; }
    }
}
