//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despachos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Despachos()
        {
            this.Chat = new HashSet<Chat>();
            this.UbicacionesServicios = new HashSet<UbicacionesServicios>();
        }
    
        public int ID_Despacho { get; set; }
        public System.DateTime Fecha { get; set; }
        public int ID_Vehiculo_Conductor { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public string UserID { get; set; }
        public int ID_Reserva { get; set; }
        public Nullable<System.DateTime> Fecha_Domicilio { get; set; }
        public Nullable<System.DateTime> Fecha_Ocupado { get; set; }
        public int ID_FormaPago { get; set; }
        public Nullable<System.DateTime> Fecha_Confirmacion { get; set; }
        public Nullable<int> Tiempo_Espera_Min { get; set; }
        public Nullable<int> Encuesta { get; set; }
        public string Encuesta_Obs { get; set; }
    
        public virtual FormasPago FormasPago { get; set; }
        public virtual Reservas Reservas { get; set; }
        public virtual Vehiculos_Conductores Vehiculos_Conductores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chat> Chat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UbicacionesServicios> UbicacionesServicios { get; set; }
    }
}
