//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flotas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flotas()
        {
            this.Vehiculos = new HashSet<Vehiculos>();
            this.Conductores = new HashSet<Conductores>();
        }
    
        public int ID_Flota { get; set; }
        public string Nombre { get; set; }
        public int ID_Calle { get; set; }
        public int Numero_Exterior { get; set; }
        public string Numero_Interior { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string RFC { get; set; }
        public int ID_Banco { get; set; }
        public string Clabe { get; set; }
        public string Email { get; set; }
        public bool Habilitado { get; set; }
        public bool Reportes { get; set; }
        public int ID_FormaPago { get; set; }
        public int ID_Afiliado { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public string UserID { get; set; }
        public bool Liquido { get; set; }
    
        public virtual Afiliados Afiliados { get; set; }
        public virtual Bancos Bancos { get; set; }
        public virtual Calles Calles { get; set; }
        public virtual FormasPago FormasPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculos> Vehiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conductores> Conductores { get; set; }
    }
}
