//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operadores()
        {
            this.Chat = new HashSet<Chat>();
            this.Llamadas = new HashSet<Llamadas>();
            this.Reservas = new HashSet<Reservas>();
            this.Sanciones = new HashSet<Sanciones>();
            this.Sanciones1 = new HashSet<Sanciones>();
        }
    
        public int ID_Operador { get; set; }
        public string Nombre { get; set; }
        public int ID_Calle { get; set; }
        public int Numero_Exterior { get; set; }
        public string Numero_Interior { get; set; }
        public int Codigo_Postal { get; set; }
        public string Telefono { get; set; }
        public string RFC { get; set; }
        public bool Habilitado { get; set; }
        public int Objetivo_Mensual { get; set; }
        public int ID_Turno { get; set; }
        public int ID_Afiliado { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public string UserID { get; set; }
        public string UserID_Operador { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    
        public virtual Afiliados Afiliados { get; set; }
        public virtual Calles Calles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chat> Chat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Llamadas> Llamadas { get; set; }
        public virtual Turnos Turnos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservas> Reservas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sanciones> Sanciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sanciones> Sanciones1 { get; set; }
    }
}
