//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntosInteres
    {
        public int ID_PuntoInteres { get; set; }
        public string Nombre { get; set; }
        public bool Habilitado { get; set; }
        public int ID_Calle { get; set; }
        public int Numero { get; set; }
        public decimal Latitud { get; set; }
        public decimal Longitud { get; set; }
        public int ID_TipoPuntoInteres { get; set; }
        public int ID_Afiliado { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public string UserID { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual Afiliados Afiliados { get; set; }
        public virtual Calles Calles { get; set; }
        public virtual TiposPuntosInteres TiposPuntosInteres { get; set; }
    }
}
