//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservas()
        {
            this.Despachos = new HashSet<Despachos>();
            this.Reservas_Rechazadas = new HashSet<Reservas_Rechazadas>();
        }
    
        public int ID_Reserva { get; set; }
        public System.DateTime Fecha { get; set; }
        public int ID_Operador { get; set; }
        public Nullable<decimal> Latitud_Origen { get; set; }
        public Nullable<decimal> Longitud_Origen { get; set; }
        public Nullable<decimal> Latitud_Destino { get; set; }
        public Nullable<decimal> Longitud_Destino { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public string UserID { get; set; }
        public Nullable<int> ID_Cliente { get; set; }
        public Nullable<int> ID_ClienteHabitual { get; set; }
        public Nullable<int> ID_ClienteAbonado { get; set; }
        public int ID_Calle_Origen { get; set; }
        public int ID_Calle_Destino { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> ID_Estatus_Reserva { get; set; }
        public int Numero_Exterior_Origen { get; set; }
        public int Numero_Exterior_Destino { get; set; }
        public Nullable<System.DateTime> Fecha_Finalizacion { get; set; }
        public int ID_TipoVehiculo { get; set; }
        public string Numero_Interior_Origen { get; set; }
        public string Numero_Interior_Destino { get; set; }
        public string Origen_App { get; set; }
        public string Destino_App { get; set; }
        public string Motivo_Cancelacion { get; set; }
        public Nullable<int> ID_Cupon { get; set; }
        public Nullable<int> ID_TarjetaCredito { get; set; }
        public string ID_Codigo { get; set; }
        public Nullable<int> ID_Reserva_Anterior { get; set; }
        public Nullable<decimal> kmAR { get; set; }
    
        public virtual Calles Calles { get; set; }
        public virtual Calles Calles1 { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual ClientesAbonados ClientesAbonados { get; set; }
        public virtual ClientesHabituales ClientesHabituales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Despachos> Despachos { get; set; }
        public virtual Estatus_Reserva Estatus_Reserva { get; set; }
        public virtual TiposVehiculos TiposVehiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservas_Rechazadas> Reservas_Rechazadas { get; set; }
        public virtual Operadores Operadores { get; set; }
        public virtual Cupones Cupones { get; set; }
    }
}
