//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas_Rechazadas
    {
        public int ID_Reserva_Rechazada { get; set; }
        public int ID_Reserva { get; set; }
        public int ID_RazonRechazo { get; set; }
        public System.DateTime Fecha_Rechazo { get; set; }
        public Nullable<int> ID_Vehiculo_Conductor { get; set; }
        public Nullable<int> Es_Conductor { get; set; }
    
        public virtual RazonesRechazos RazonesRechazos { get; set; }
        public virtual Reservas Reservas { get; set; }
    }
}
