//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguimiento_Despacho_Detalle
    {
        public int ID_Seguimiento_Despacho { get; set; }
        public string LatLng { get; set; }
        public Nullable<int> step { get; set; }
    
        public virtual Seguimiento_Despacho Seguimiento_Despacho { get; set; }
    }
}
