//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguimiento_Despacho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seguimiento_Despacho()
        {
            this.Seguimiento_Despacho_Detalle = new HashSet<Seguimiento_Despacho_Detalle>();
        }
    
        public int ID_Despacho { get; set; }
        public int ID_Vehiculo_Conductor { get; set; }
        public int ID_Seguimiento_Despacho { get; set; }
        public string Inicio { get; set; }
        public string Fin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguimiento_Despacho_Detalle> Seguimiento_Despacho_Detalle { get; set; }
    }
}
