//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SistemaVariables
    {
        public int sivaID_SISTEMA_VARIABLES { get; set; }
        public string sivaVARIABLE { get; set; }
        public string sivaVALOR_STRING { get; set; }
        public Nullable<long> sivaVALOR_INT { get; set; }
        public Nullable<double> sivaVALOR_DOUBLE { get; set; }
        public Nullable<int> sivaDOMINIO { get; set; }
        public bool Eliminado { get; set; }
    }
}
