//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarifas()
        {
            this.TiposVehiculos = new HashSet<TiposVehiculos>();
        }
    
        public int ID_Tarifa { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public decimal Tarifa_Minima { get; set; }
        public decimal Precio_Base { get; set; }
        public decimal Precio_Km { get; set; }
        public decimal Precio_Min { get; set; }
        public int ID_Afiliado { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public string UserID { get; set; }
        public bool Activa { get; set; }
    
        public virtual Afiliados Afiliados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TiposVehiculos> TiposVehiculos { get; set; }
    }
}
