//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones
    {
        public int Id_Transaccion { get; set; }
        public int Id_Cliente { get; set; }
        public Nullable<int> Id_Reserva { get; set; }
        public int Id_TipoTransaccion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Referencia { get; set; }
        public string Numero_Control { get; set; }
        public string Codigo_Autorizacion { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Respuesta { get; set; }
        public string Accion { get; set; }
        public string Observaciones { get; set; }
    }
}
