//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_App
    {
        public int ID_Usuario { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public int Activo { get; set; }
        public string Token { get; set; }
        public string Clave { get; set; }
        public string Telefono { get; set; }
        public int ID_Cliente { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public string appid { get; set; }
        public string FBId { get; set; }
        public string Codigo { get; set; }
        public string Dispositivo_Id { get; set; }
        public string Fecha_Cumpleans { get; set; }
        public Nullable<decimal> Abono { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
