//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClientes
    {
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public int Activo { get; set; }
        public string Telefono { get; set; }
        public string Fecha_Cumpleans { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public int ID_Cliente { get; set; }
    }
}
